apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nginx-secret
  namespace: external-secrets
spec:
  refreshInterval: "5m"
  secretStoreRef:
    name: aws-secret-store
    kind: ClusterSecretStore
  
  target:
    name: nginx-credentials

  data:
  - remoteRef:
      key: nginx-password
      property: password 
    secretKey: nginx-pod-password