apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nginx-secret
  namespace: external-secret
spec:
  refreshInterval: "5m"
  secretStoreRef:
    name: aws-secret-store
    kind: SecretStore
  
  target:
    name: nginx-credentials # Kubernetes Secret Name

  data:
  - secretKey: nginx-pod-password # Kubernetes Secret Key
    remoteRef:
      key: nginx-password # AWS Secret Manager Secret Name
      property: password # AWS Secret Manager Secret Key
    

