apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx-web
  name: nginx
  namespace: external-secret
spec:
  containers:
  - image: nginx
    name: nginx-web
    volumeMounts:
      - name: nginx-password
        mountPath: /etc/secrets
  volumes:
  - name: nginx-password
    secret:
      secretName: nginx-credentials    
  dnsPolicy: ClusterFirst
  restartPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx-web
  namespace: external-secret
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    name: http-service
  selector:
    app: nginx-web
